#!/usr/bin/perl

my $LOGFILE = "/home/embroede/sensor/log/Check_Network.log";

my @output = `pgrep Check_Network`;
if (scalar @output > 1) {
    print "Check_Network is already running, exiting...\n" if $ARGV[0] eq "-d";
    exit 0;
}

my $connected = 0;
my @interfaces = `/sbin/ifconfig`;
@interfaces = grep(/inet addr/, @interfaces);
chomp @interfaces;
foreach my $interface (@interfaces) {
    next if $interface =~ /127\.0\.0\.1/;
    $connected = 1;
    print "Found a connection!\n" if $ARGV[0] eq "-d";
}
if (!$connected) {
    print "No network connection, restarting networking service\n" if $ARGV[0] eq "-d";
    open(FH, ">", $LOGFILE) or die "Couldn't open $LOGFILE: $!\n";
    print FH "No IPv4 address, restarting network with /etc/init.d/networking restart\n";
    close(FH) or die "Couldn't close $LOGFILE\n";
    `/etc/init.d/networking restart`
}

