#!/bin/bash
filename=${1-`date +%FT%H:%M:%S`}
raspivid --width 1280 --height 720 --framerate 30 --bitrate 750000 --qp 20 --timeout $((20*1000)) --rotation 270 --output /tmp/video
avconv  -y -framerate 24 -i /tmp/video -c copy /var/www/sensor/videos/$filename.mp4 >& /dev/null
